haproxy:
  extends:
    file: haproxy.yml
    service: haproxy-server
  environment:
    - "constraint:node==swarm-0"
web:
  image: alvinr/demo-webapp
  extends:
    file: haproxy.yml
    service: haproxy-app
  environment:
    - MONGO_HOST=prod_mongodb_1
mongodb:
  image: mongo
  environment:
    - "constraint:node==swarm-0"
  command: --smallfiles --noprealloc